### ISSUE TITLE
Automatically detect the current repository when running a pipeline

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1026]
This makes the repository parameter optional

**Comment by rberrelleza** [comment]
`git config --get remote.origin.url` gets you the URL of the remote, it's a good way to start. Since pipeline expects https:// as the protocol, instead of git, we would need to either:
- fail and mention that we only support http
- translate the URL (we could do this only for well known providers like github, gitlab and bitbucket as a start)
