### ISSUE TITLE
"okteto stack deploy --build" should be the default behavior

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1098]
**Is your feature request related to a problem? Please describe.**
Deploying without building could be supported with the `--no-build` flag.

**Comment by rberrelleza** [comment]
I think it's better to align with the default behavior of docker-compose, and don't build by default. I find it more obvious when there's a --build flag that adds a new behavior on top of the default, rather than have to tell it what not to do.

I also  feel like in most cases I'd rather not have to wait for things to be build, and have my application up and running as quick as possible.

**Comment by rlamana** [comment]
Doesn't `docker-compose up` build the images if they are missing?? I've never had to use the `--build` parameter with `docker-compose up`, and I expect that behavior when using `okteto stack deploy`

**Comment by pchico83** [comment]
`docker-compose up` only builds images if they are missing.
The equivalent would be to build images only if they don't exist on the okteto registry.
