### ISSUE TITLE
 Unknown syncthing error

### ISSUE THREAD

**Issue by mgingios** [okteto/okteto#1126]
I have a custom Docker image that contains the Java tools that I use.  It launches fine in Docker on my machine, so it should be okay in Okteto.  I am sharing the image and Dockerfile at the following locations, in case they may be helpful:

- docker pull abitofhelp/okteto-jvm
- https://gitlab.com/abitofhelp.shared/okteto/jvm
---------------------------------
> okteto up
Deployment csc doesn't exist in namespace default. Do you want to create a new one? [y/n]: y
 ✓  Development container activated
 x  Unknown syncthing error

**Comment by pchico83** [comment]
@mgingios thanks for all the details to troubleshoot the issue. Having a look...

**Comment by pchico83** [comment]
@mgingios looks like the folder where code is synchronized is full. I would suggest to do two things:
- Define a `.stignore` file with the files you don't need to synchronized. For example, `.git`, `.gradle` or `build`.
- Increase the okteto volume size: https://okteto.com/docs/reference/manifest#persistentvolume-object-optional
I will create an issue because you should have got a clearer error.

**Comment by pchico83** [comment]
Fixed by #1168
