### ISSUE TITLE
Support for deployments launched by flux v2

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1253]
**Is your feature request related to a problem? Please describe.**
Flux v2 no longer supports using the `flux.cd/ignore` annotation to tell it to stop watching a deployment. Instead, it expects their CRD objects to be updated with a `spec.ignore` property.  

Without this, it's very hard for `okteto up` to integrate with deployments managed with fluxV2, since the development environments get constantly redeployed as okteto and flux fight for control.

**Describe the solution you'd like**
@kingdonb  suggested that okteto could automatically add the `spec.ignore` property to the flux object when I run `okteto up` and to remove it when I run `okteto down`. The resource name and path to patch should be defined in the manifest.

**Describe alternatives you've considered**
Add support for a  `pre up hook` and `post up hook` so a user can add scripts to customize things on the fly.

**Additional context**
https://cloud-native.slack.com/archives/C01A402P0R2/p1611849846069900

**Comment by kingdonb** [comment]
Yes, `spec.ignore` or `spec.suspend`

In the Flux v2 architecture, there are CRD reconcilers or operators, in most cases there will be at least two reconcilers connected in a chain, (eg. `GitRepo` that feeds into a `Kustomization` which drives changes in a `HelmRelease`)

Use cases will vary so I can imagine in the most specific case, `spec.ignore` being used to prevent the cluster reconcilers from overwriting Okteto's changes to my one dev deployment that has been patched through `okteto up` – you would either `suspend` the HelmRelease or `ignore` it in the Kustomization that applies it. Possibly both. Maybe you're not using helm-controller and a single `ignore` in the `Kustomization` is enough to stop you from losing your TTY when the reconciliation loop runs again.

Then you may have someone in a production use case, where they are deploying an okteto pod for debugging production, and they have very carefully specified the readiness checks and all appropriate default overrides in okteto.yml to continue so that production users are not impacted in any way by the debug session... but since the developers are distributed across time zones and hard to reach all at once, we're not going to bother them, just block them from making changes. So they want all changes of any kind to be paused until the debugging session is completed and deployments can be reverted to normal. Maybe more controllers have been added since Okteto built in some manner of support for Flux 2, and we want to be sure those can be manipulated in a similar way as well.

I can't think of any specific use cases that wouldn't be enabled through addition of a simple `pre up hook` and/or `post up hook` as you proposed, although you may also need `pre-down` and `post-down`. (Are there also more different hooks that we might want to add?)

**Comment by pchico83** [comment]
@kingdonb is this still needed? do you think someone from weave could work on it?
