### ISSUE TITLE
okteto init adds both forward and remote with the same port

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1902]
![image](https://user-images.githubusercontent.com/475313/139507590-3cda139e-c064-4fa6-826f-069ed3e8f53c.png)

During okteto up, I get the following error:

```
 i  Using rberrelleza @ cloud.okteto.com as context
 ✓  Persistent volume successfully attached
 ✓  Images successfully pulled
 x  Couldn't connect to your development container: port 9000 is listed multiple times, please check your forwards configuration
```

**Comment by Youngestdev** [comment]
Hi! I'll be looking into this. 

Quick question: Is this a general issue as the `okteto init` command assigns the same value for reverse and forward port for only this sample ( https://github.com/okteto/php-with-nginx ). I tested for other sample and it didn't assign the same ports.

**Comment by rberrelleza** [comment]
I think this sample is triggering a behavior we need to fix. `okteto init` shouldn't add the same port on the `forward` and `reverse` sections of okteto.yaml. If port 9000 (for example) was already taken by forward, we should either pick an alternative port on `reverse`or skip it from the configuration to prevent the clash.

**Comment by pchico83** [comment]
@Youngestdev each language we support with `okteto init` has a set of default values, including debug ports:
https://github.com/okteto/okteto/blob/master/pkg/linguist/dev.go#L58

Also, we get the current ports from the running deployment. We don't handle if there is a collision between both of them. If these cases, I would remove the default debugger port we are adding.

In order to repro it, you could create a python hello world application lisrening on port 9000:
https://github.com/okteto/okteto/blob/master/pkg/linguist/dev.go#L129

**Comment by Youngestdev** [comment]
Oh! Thank you for more context @pchico83 and @rberrelleza
