### ISSUE TITLE
`okteto deploy` should start the `init` sequence if no okteto manifest is found or can be inferred

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2203]
**Is your feature request related to a problem? Please describe.**
This way, we can educate our users to clone their repo and just run `okteto deploy`.

After deployment is successful, https://github.com/okteto/okteto/issues/2202 will show the CTA to `okteto up`

**Comment by jLopezbarb** [comment]
Is this still required? I don't think okteto deploy should start the init sequence since we couldn't find anything to deploy already (no manifest found or inferred). I think that `okteto deploy` should only deploy and show the CTA to `okteto up` and `okteto up` is the one which must call the okteto init if needed, which is the way is right now. WDYT?

**Comment by pchico83** [comment]
@jLopezbarb let's close this for now until we rethink how `okteto init` works
