### ISSUE TITLE
Fix vulnerabilities reported by trivy

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2420]
<img width="1250" alt="Screenshot 2022-03-24 at 10 38 12" src="https://user-images.githubusercontent.com/7474696/159887556-3b9f8865-70cf-4101-84d8-134f1f80ca3a.png">

**Comment by pchico83** [comment]
@maroshii why did you close this one? we rate F on cloudbin because of the cli CVEs

**Comment by maroshii** [comment]
My bad, I thought this was attached to the chart release

**Comment by teresaromero** [comment]
what would be the requirements to make this issue done? should we use the scan channel at slack and upgrade packages that are tagged as high/medium? 

cc: @pchico83 @jmacelroy

**Comment by teresaromero** [comment]
- [ ] CVE-2022-27191 - crypto at backend - https://github.com/okteto/app/pull/3944

**Comment by maroshii** [comment]
@teresaromero I'd say this issue tracks one-off vulnerabilities fixes. Fixing vulnerabilities is a moving target so we would never close this out. The ones you mentioned should be enough to close this issue since we already removed a lot from the report by removing cloudbin. Not sure how realistic it is to remove the ones in buildkit cc @jmacelroy 

The ultimate goal is to move scanning into CI using something like https://github.com/okteto/scan in case you are interested in looking into that automation a little bit more.

**Comment by jmacelroy** [comment]
We won't be able to address the buildkit ones last time I looked. I will look again closer to release.

**Comment by jmacelroy** [comment]
In order to close this issue we'd need to address all of the issues that we are able to and evaluate the remaining ones for impact.

**Comment by teresaromero** [comment]
https://github.com/okteto/app/pull/3944
https://github.com/okteto/app/pull/3946

Release done to cloud https://github.com/okteto/app/releases/tag/1.12.113

**Comment by pchico83** [comment]
This is a continuous efort. We should create more specific issues when we want to solve a given vulnerability
