### ISSUE TITLE
Create an e2e tests that deploys a subset of services

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2611]
We can use https://github.com/okteto/microservices-demo-compose

The test should be running `okteto deploy vote` and check that:
1. Only vote service has been built
2. Dependent services has been deployed `[postgresql, kafka, zookeeper]`
4. Other services are not deployed `[result, worker]`
5. Only volumes that are in the services deployed has been created

**Comment by pchico83** [comment]
Also, only the affected endpoints are deployed

**Comment by pchico83** [comment]
> > Also, only the affected endpoints are deployed
> 
> I didn't add it because main branch didn't have that, Should we create a branch for it?

Yes, we should do the same with endpoints. only deploy what's needed

**Comment by jmacelroy** [comment]
@jLopezbarb When would like to get this done? It seems like a good and important test to add. Should it be top of the stack for cli? Would you be willing to postpone anything in the next release for it. What do you think @pchico83

**Comment by jLopezbarb** [comment]
I would schedule it for next milestone, it's an easy test to create and provides so much value

**Comment by AdrianPedriza** [comment]
if we use [microservices-demo](https://github.com/okteto/microservices-demo-compose) as app to deploy we cannot check that the needed volumes has been created due to `okteto deploy vote` doesnt requires postgresql (is not a dependency). To be able to deploy postgresql as replicaset and check that the needed volumes has been created we will need to add postgresql as depend_on service in vote service spec (even if it really isn't)
