### ISSUE TITLE
Set dockerfile and context defaults and warn if dockerfile is not in relative path to context

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2636]
**Describe the bug**
If I have an image on the `build` section that sets the `context` field, the value for `dockerfile` should be relative to the `context` field. In particular, if not defined, it should default to `context/Dockerfile`.

**To Reproduce**
Remove this line:
https://github.com/okteto/movies/blob/main/okteto.yml#L6

and run `okteto build frontend`. It should work because that should be the default value of the `dockerfile` field.

**Comment by mnevadom** [comment]
If context is filled and dockre file isn't, dockerfile = context/Dockerfile. 

But to be sure, if both are filled, the path from dockerfile is relative to context value or to "."?

Btw, is the line 7 we should remove to test it right?

**Comment by pchico83** [comment]
> If context is filled and dockre file isn't, dockerfile = context/Dockerfile.
> 
> But to be sure, if both are filled, the path from dockerfile is relative to context value or to "."?
> 
> Btw, is the line 7 we should remove to test it right?

@mnevadom yes to all :-)

**Comment by mnevadom** [comment]
Im trying to force the error with the latest version of the CLI after reviewing the code. 
And Im not getting the error by deleting the line: 
   
   - dockerfile: frontend/Dockerfile

I think it makes sense that is already working what I understand from the issue, because first when GETTING the values from manifest, it does this: 

`
                 if !(b.Image != "" && len(b.VolumesToInclude) > 0 && b.Dockerfile == "") {
			b.setBuildDefaults()
		}
`

![image](https://user-images.githubusercontent.com/16018223/169257553-2469d975-ac6c-46e3-a1b8-ddc61230759a.png)


Setting a default value to dockerfile. 

And it tries to get the value to use it, if not found in dir, then it will try to find it in "context" dir: 

`file := b.Dockerfile
	if !filepath.IsAbs(b.Dockerfile) && !model.FileExistsAndNotDir(file) {
		file = filepath.Join(b.Context, b.Dockerfile)
	}`

I think there is just one scenario when it wont work, if you have filled volumes Dockerfile is empty, image has value and you add volumes. Then I belive dockerfile will be empty, and then when reading it we wont be able to get the Dockerfile. 



Maybe just adding this when reading the manifest before: 

![image](https://user-images.githubusercontent.com/16018223/169258425-e82be1e3-abec-4edf-9eaa-68674e6fa630.png)


Should do for fixing the issue in that specific scenario right?

**Comment by pchico83** [comment]
@mnevadom seems like the issue was fix as part of the build refactor in 2.3.0.
I would take the opportunity to refactor this code in a single function while deserializing the compose/okteto manifest, since the logic is now split in many `if's` across the source code

**Comment by mnevadom** [comment]
It will also change one particular scenario: 

If the user has two Dockerfiles, in root and in context, and he fills the manifest with "Dockerfile", it will show a warning message, but NOW is taking the context file, not the root one
