### ISSUE TITLE
okteto deploy [svc] doesnt show all the actual dependencies of a service

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/okteto#2674]
**Describe the bug**
if I run `okteto deploy vote` (which depends on kafka and postgresql and kafka in turn depends on zookeper) the log shows me as a warning **The following services need to be deployed because the services passed as arguments depend on them: [kafka, postgresql]**. Shouldn't zookeper also appear? It seems that 'non direct' dependencies are not shown.

**To Reproduce**

1. Cone https://github.com/okteto/microservices-demo-compose
2. Execute `okteto deploy vote`
3. See logs

**Expected behavior**
In my opinion, the log should also show the 'non-direct' dependencies and therefore wait until they are deployed before deploying the desired service.

- OS: macOS
- Version Okteto CLI 2.2.0

**Additional context**
Current behavior: 
<img width="1029" alt="Captura de pantalla 2022-05-11 a las 10 07 15" src="https://user-images.githubusercontent.com/22500940/167802904-67270fda-0fbd-4bbd-b825-36e369fb0bea.png">

**Comment by jmacelroy** [comment]
I wonder if we should continue down the path of indirect deps or not? It's my understanding that zookeeper is a dep of kafka. When you deploy kafka does it correctly address the zookeeper dependency. I'd actually be in favor of only showing direct dependencies due to the complications that can occur. 

How did you come across this @AdrianPedriza?

**Comment by jLopezbarb** [comment]
I think this was fixed. @AdrianPedriza could you try again?

**Comment by AdrianPedriza** [comment]
@jLopezbarb yes, issue is not reproducible anymore. I will close it.
