### ISSUE TITLE
Adapt examples to be used in vanilla clusters

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/okteto#2694]
**Is your feature request related to a problem? Please describe.**
In order to be able to add new features such as e2e testing using kinD (#2465) , it is necessary to address this problem. (See #2637)

**Describe the solution you'd like**
Solution would be to adapt our examples to cases where vanilla clusters are used.

**Comment by jmacelroy** [comment]
@AdrianPedriza Is there anything blocking starting progress on this. Is it possible we could start with a few key examples instead of adapting all of them. Possibly movies, multirepo-demo and microservices-demo?

I see the related issue is in tracking. If you're not opposed I'm going to put the related issue blocked by this back on the backlog and put this issue in specification stage for the same release.

**Comment by AdrianPedriza** [comment]
> @AdrianPedriza Is there anything blocking starting progress on this. Is it possible we could start with a few key examples instead of adapting all of them. Possibly movies, multirepo-demo and microservices-demo?
> 
> I see the related issue is in tracking. If you're not opposed I'm going to put the related issue blocked by this back on the backlog and put this issue in specification stage for the same release.

OK, I think as a POC adapting just a few samples is a good idea but first of all I think it will be necessary to clarify how we want to approach #2637 in order to be able to continue with this one. WDYT?

**Comment by jLopezbarb** [comment]
With the latest changes done to the e2e tests, we could run all e2e in a vanilla cluster except the ones on the `okteto` folder which need to have an okteto platform installed in order to work

**Comment by jLopezbarb** [comment]
Closing this since the new e2e tests provides the correct way of doing it instead of changing all the examples
