### ISSUE TITLE
Volumes Not Always Removed with Down and Destroy Commands

### ISSUE THREAD

**Issue by jmacelroy** [okteto/okteto#2759]
**Describe the bug**
This flow was identified by a prospective Customer.  They initially did 'CLI: okteto destroy' but realized their volumes (in the UI) were still alive.  They attempted 'CLI: okteto destroy -v' and it will not go back and clean up the volumes.  However, has they originally ONLY executed 'CLI: okteto destroy -v' the desired fully clean state is achieved.  As an end user, you may not realize volumes are present so being able to go back and re-run the command with the flag(s) would be an expected behaviour.

**To Reproduce**
Steps to reproduce the behaviour.  This example only creates and destroys a namespace with no other operations in between.

1. Create a new namespace e.g. 'foo' on demo.okteto.dev
2. Launch a new development environment from the UI
3. Clone code locally & set context to demo / namespace to 'foo'
4. Reproduce error by destroying without specifying volumes then attempting to destroy with volumes
5. $ okteto destroy # notice Volumes in UI remain as Unused
6. $ okteto destroy -v # notice Volumes in UI remain as Unused
7. $ kubectl get pvc # shows that the volumes still remain

NOTE 1#: If instead you originally executed only "$ okteto destroy -v" in step #5 , everything gets cleaned up as expected.

NOTE 2#: In addition, In between steps 3# and 4#, we did an  'okteto up vote' followed by 'okteto down -v vote' and the outcome described above was the same.

**Expected behavior**
Executing "CLI: okteto destroy" followed by "CLI: okteto destroy -v" should have the same outcome as only executing "CLI: okteto destroy -v".   From a users perspective, specifying the volumes can easily be overlooked so they should be able to re-execute to clean things up.

**Desktop (please complete the following information):**

- OS: MacOS
- Okteto CLI: 2.3.2

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by ifbyol** [comment]
I know what the issues is. When a statefulset defines a volume using volumeClaimTemplate, that is created directly by the kubernetes controller so it doesn’t pass through our proxy and the `deployed-by` label is not added to the volume.

In that case, if you have executed `okteto destroy`, volumes are not deleted and if you try to do it executing `okteto destroy -v` after that, it won’t delete the volumes because they don’t have the label.

When you execute directly `okteto destroy -v` for the first time, volumes are deleted because we first list all the volumes for statefulsets with the `deployed-by` label and delete them. After that, everything else is deleted. That is the reason why volumes are deleted when everything else is deployed.

One option to solve this is to include the label if a statefulset has set the `.spec.volumeClaimTemplates` property when is being processed by the proxy [here](https://github.com/okteto/okteto/blob/670d6f722d086352a9c3900f89623d535dcf0a7e/cmd/deploy/proxy.go#L355)

**Comment by jLopezbarb** [comment]
Reopen since we have reverted the changes related to this fix. We need to think in another solution for this problem since it was preventing to redeploy statefulsets with volume claims

**Comment by pchico83** [comment]
@jLopezbarb one option here if to list PVC after `okteto deploy` and add the label manually. This way they get the label, but we don't need to modify the statefulset volume claim template
