### ISSUE TITLE
GraphQL client not parsing Metadata from errors

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#2926]
**Is your feature request related to a problem? Please describe.**
When implementing a new API Error which is thrown with Metadata using GraphQL Extensions, the CLI is not capable to get this Metadata

**Describe the solution you'd like**
CLI is able to interpret a GraphQL Error with Metadata 

Found while implementing https://github.com/okteto/okteto/pull/2923

**Comment by ifbyol** [comment]
This is due to the library we use for doing graphql requests. When there is an error in the request, they are just getting the `Message` and the `Localtions`.

We might need to check if there is a newer version of the library which supports it or we might need to use another library.

This only affects when using GraphQL Extensions as Tere mentioned

**Comment by jLopezbarb** [comment]
Reopening since it's not completed
