### ISSUE TITLE
Build images locally without the build service

### ISSUE THREAD

**Issue by odedlaz** [okteto/okteto#2993]
**Is your feature request related to a problem? Please describe.**

If my okteto context points to an Okteto URL, images are built using the `Okteto Build Service`.
I would like to control this behavior and build images locally as well.

Why? Building in okteto cloud can be slower than building locally. Moreover, builds don't run in parallel.

**Describe the solution you'd like**

A new `--local` knob to the `build` command that builds dockerfiles locally, in parallel. This feature is dependant on #2921.

**Describe alternatives you've considered**

Build an external script that build the images locally and pushes them to the okteto cloud registry.

**Additional context**

I would like to implement this myself. This issue is to make sure I won't waste my time if I post a PR and get rejected :)

**Comment by jmacelroy** [comment]
My intuition is that we'd rather work towards having the images build faster on Okteto and understand what may be making them slow in your case. Typically we see images being built much faster due to the use of a shared cache and build optimizations. 

Also, the images will need to be pushed to the cluster eventually and having them local may build them faster but is often offset when having to push images repeatedly to a remote system. So, I'm wondering if the entire cycle is being accounted for and is still slower, and if so I'm curious if different Dockerfile optimizations can be done to achieve both fast builds, shared cache and less network transfers.

**Comment by pchico83** [comment]
Yes, I agree with @jmacelroy. We should understand why the remote build is slower than building locally

**Comment by pchico83** [comment]
@odedlaz another option here is to set `BUILDKIT_HOST` to point to your local buildkit address

**Comment by pchico83** [comment]
@odedlaz I am closing this one. Let me know if you still find valuable the use case

**Comment by nhuizenga** [comment]
I'd like to request that this issue be reopened. For reference, we use self-hosted Okteto clusters (yes, plural). We have a use case that involves a rather large image and in order to build on the cluster, we had to provision nodes with 64GB of memory which are, as you might expect, quite expensive. The build in question is 5M+ LoC and building pegs out 16 cores for a 20-25 minutes. The resulting image is in excess of 2GB. This image is a common dependency for a lot of microservices in our org since it is our legacy monolith. That means we need to deploy it often, but most engineers don't actually need to make many changes to it.

The saving grace is that at runtime, other than the disk impact of the giant image, the application is pretty light on footprint (<2GB memory, ~1-2 cores). Our engineers already have machines that can build this beast and transferring 2GB of image isn't _too_ bad in terms of time. Being able to build it locally, then push to the registry would be a significant improvement for us.

I had hoped that I could at least `docker push` my image to Okteto's registry, but it appears that is not possible without me cracking open the auth used for it. If I could do that, then I could `okteto deploy --no-build` to get it deployed.
