### ISSUE TITLE
misleading logs while initialising volumes

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3060]
**Describe the bug**
When Okteto is initialising the volumes on the init containers, the message given to the user can be misleading 

<img width="915" alt="Captura de pantalla 2022-09-01 a las 17 27 52" src="https://user-images.githubusercontent.com/25170843/187961689-f8673dd3-a620-42ae-98a5-221b3059a0a8.png">

**To Reproduce**

1. Copy the following `docker-compose`:
```yaml
services:
  queue:
    image: rabbitmq
    volumes:
      - /etc/nats-server.conf
```
1. Check pod logs on the UI or by running `kubectl logs queue-0 -c init-volume-queue`
1. Check that the logs are not clear enough

**Expected behavior**
I expect to have a better log message, something like:
`initilizing volume ${VOLUME_NAME} with content of the image ${INIT_CONTAINER_IMAGE}` instead of `initializing volume...`
and 
`the image ${INIT_CONTAINER_IMAGE} doesn't have any content at ${PATH_TO_INIT}` instead of `cp: cannot stat '${PATH_TO_INIT}.': No such file or directory`

**Desktop (please complete the following information):**

- Version 2.6

**Comment by AdrianPedriza** [comment]
It is necessary to reopen the issue since the [PR](https://github.com/okteto/okteto/pull/3127) that implemented it was reverted because it was not taking into account images with the format `img-repo/img-name`, it was only taking into account `img-name`, so the tests to be implemented should cover both possibilities. Comments to take into account about the PR that was reverted:

`It feels very verbose.  I would check if the folder exists (instead of using sed). And then show all the cp output in case of error.
As a follow-up issue, we could inject a binary that does this logic instead of adding a long command in the pod manifest`

There is an [issue](https://github.com/okteto/okteto/issues/3240) asking about refactoring the init container command so only what is in the description should be addressed.

**Comment by jLopezbarb** [comment]
Reopening since it's not completed

**Comment by jLopezbarb** [comment]
Not implemented
