### ISSUE TITLE
`namespace` is missconfigure when using `context` in my okteto manifest

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3134]
**Describe the bug**
My current context is pointing to https://cloud.okteto.com to a different namespace than the personal namespace.
If I have a manifest with the `context` field like this:

```
context: https://cloud.okteto.com
```

and run any cli comand, the command is executed in my personal namespace. But it should use my current context namespace, because I am already working on https://cloud.okteto.com.

I didn't check when the context is a kubernetes context, but we should do the same. If the context in the okteto manifest is the same as the current okteto context, keep using the namespace in the current okteto context.

**Comment by abs007** [comment]
So from what I can understand, there's a namespace switching after running `okteto up`. Also, will a local minikube context work as a  Kubernetes context?

**Comment by jLopezbarb** [comment]
> there's a namespace switching after running okteto up

Yes, It seems that `okteto up` is using the context stored in the user okteto context instead of the one that is specified in the manifest.

> will a local minikube context work as a Kubernetes context?

Yes, it will

**Comment by abs007** [comment]
Got it. I'd like to work on this issue. Also, could I get some pointers as to which file I should look into? Thanks

**Comment by jLopezbarb** [comment]
Not quite sure, but I think we should set also the namespace if the context is already set in the config.json [here](https://github.com/okteto/okteto/blob/fbabbedb0ebc083ceacf3e264994bd5c4a7c4cb6/cmd/context/create.go#L146). If we don't set it as ctxOptions [this function](https://github.com/okteto/okteto/blob/fbabbedb0ebc083ceacf3e264994bd5c4a7c4cb6/cmd/context/create.go#L228) will get the default value and set it

**Comment by abs007** [comment]
Also, in [here](https://www.okteto.com/docs/reference/manifest/#context-string-optional) it mentions that "*By default, it uses the current okteto context.*" Could I get some more info into what the **current okteto context** is. Is it the context that we choose when we initially run `okteto up`?

**Comment by abs007** [comment]
Hi, I'm not sure if I'll be able to reproduce this bug since I do not have a business email.

**Comment by jLopezbarb** [comment]
Hi @abs007, 

> Also, in [here](https://www.okteto.com/docs/reference/manifest/#context-string-optional) it mentions that "By default, it uses the current okteto context." Could I get some more info into what the current okteto context is. Is it the context that we choose when we initially run okteto up?

By default okteto uses the information on `~/.okteto/context/config.json` but it can be overwritten by the user if the user specifies in the Okteto manifest the context field, for example like in:
```yaml
context: https://cloud.okteto.com
name: dotnetapp
image: okteto/dotnetcore:3
sync:
- .:/usr/src/app
forward:
- 8080:8080
```

The problem here is that when the context specified in the okteto manifest is present we get the personal namespace of that context and token instead of checking if the context set by user in the manifest is already declared in the  `~/.okteto/context/config.json`, which in that case, we should use the namespace that is set there.

Since you can't test it, the only solution that I can give you is that we test the pull request whenever is done and give you feedback based on the tests that we make
