### ISSUE TITLE
`okteto build` doesn't work if an okteto manifest is not provided/found

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#3157]
**Describe the bug**
If I have a folder with a Dockerfile but I don't have any Okteto manifest, when I try to build the image with `okteto build -t <my-tag> .`, it fails with the following error:

```
 x  Could not detect any okteto manifest
    If you have an okteto manifest file, use the flag '--file' to point to your okteto manifest file

```

It stopped working on `2.7.0`

**To Reproduce**

1. Create an empty folder with a simple Docker inside it
2. Execute `okteto build -t <my-tag> .`
3. The error commented in previous section is displayed and the image is not built

**Expected behavior**
It should build the image without asking for an Okteto manifest and should behave as it was prior `2.7.0`

**Desktop (please complete the following information):**

- Version: `2.7.0` and master

**Comment by rberrelleza** [comment]
I find the proposed behavior very confusing. `okteto build` is meant to be used to build the images defined on your okteto manifest, not as a general-use tool for building containers (it's described like this on the help text for the command).  Do we have a lot of people using it like you suggest @ifbyol ?

In the last iteration of the docs that @pchico83 sent, it was defined that the behavior for building a docker image that is not defined on your okteto manifest is to pass the path of the Dockefile (.e.g okteto build -f `Dockerfile -t foo:bar`). I don't think we should introduce yet another way to do container builds. 

Is the use case of using `okteto build` to define images not defined on your manifest popular within our community? If so, I think that we should solve that by introducing a new command for that, rather than giving `okteto build` two different 'build image' modes.

**Comment by ifbyol** [comment]
@rberrelleza The expected behavior described is how the build command was working until we changed the behavior unexpectedly on `2.7.0` and without announcing it in any release note

It was how the build command was working before `2.0.0` and we kept the behavior for backward compatibility. Old pipeline files could rely on this and we didn't let them know about this change, so when we start using `2.7.0` in the installer jobs we might see an increase of reports regarding this error.

**Comment by pchico83** [comment]
@rberrelleza the issue is to solve a breaking change (with high risk of affecting existing users of okteto pipelines), not to define the new behavior. 
I agree we need to redefine the UX of `okteto build` if there isn't a manifest, but that would be part of a major release.
@jLopezbarb do we have metrics for the case the build command is using an okteto manifest or not?

**Comment by jLopezbarb** [comment]
Not right now, We can add these metrics as part of this PR. Despite of that I think we need to revisit all the metrics that we are sending since there are lots of things that we are missing

**Comment by pchico83** [comment]
@jLopezbarb yes, let's add a metric for that, it will help in future analysis to understand how often people rely on this behavior
