### ISSUE TITLE
Show spinner while checking if the image needs to be built

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3433]
**Is your feature request related to a problem? Please describe.**
We don't show a spinner while we are checking if images needs to be built. This is a bad UX since the user can think that okteto has hanged up if the user has several images to check or if his internet connection is slow.

**Describe the solution you'd like**
I'd like to have a spinner showing: "Checking images that needs to be built" or a similar message that shows what okteto is doing in that moment

**Additional context**
Function that checks if images needs to be built: https://github.com/okteto/okteto/blob/master/cmd/build/v2/services.go#L31

**Comment by NitishKumar06** [comment]
I'm working on this

**Comment by NitishKumar06** [comment]
Hi @jLopezbarb this is my first time coming up with a coding issue and needs some guidance. I'm unable to reproduce this issue. Here's what I've done till now:

1. Read about `okteto build` from okteto docs
2. Understood how important is Dockerfile to build image using okteto. However I'm not able to find when do we come across this log _Build section is not defined in your okteto manifest_? I've pushed the image to docker registry and tried to play with Dockerfile and `okteto.yml` but okteto do search for `Dockerfile` instead of `okteto.yml` which makes me wonder _what is the use case of okteto.yml when we have Dockerfile defined already?_
3. Please guide me further on how to reproduce this issue. I'm eager to make a contribution here.

Thank you!

**Comment by jLopezbarb** [comment]
Hi @NitishKumar06, I'm sorry I forgot to put some steps to reproduce the issue. Here is how to reproduce the issue:

1. Create the following Dockerfile (I usually create this one since it's 
```Dockerfile
FROM alpine
RUN echo hola
``` 

2. Create the following okteto manifest (create more services if you want to have more time between the messages):
```yaml
build:
  svc1:
    dockerfile: Dockerfile
  svc2:
    dockerfile: Dockerfile
  svc3:
    dockerfile: Dockerfile
  svc4:
    dockerfile: Dockerfile
  svc5:
    dockerfile: Dockerfile
```
3. Run `okteto deploy`: This will check if the services are built and start building the services. Notice that the time between the message `i  Using jlopezbarb @ cloud.okteto.com as context` and the next one is quick large without any input
4. If you run `okteto deploy` again you will see that between `i  Using jlopezbarb @ cloud.okteto.com as context` and the next message  is `i  Images were already built.`. We should show an spinner at the start of [this function](https://github.com/okteto/okteto/blob/master/cmd/build/v2/services.go#L31).

Let me know if you need anything else to complete the issue

**Comment by NitishKumar06** [comment]
Thanks, this worked! I'll be moving on to understanding the function and would get it done soon.
