### ISSUE TITLE
When destroy an environment, the message says "deploying development environment"

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#3450]
**Describe the bug**

When destroying an environment, the message says "deploying development environment". it should say "destroying development environment". 

![image](https://user-images.githubusercontent.com/475313/225524103-7b192504-6a68-49a8-92c7-a8f1771be78f.png)

**To Reproduce**

1. `okteto destroy`
- OS: macOS
- Version 2.13

**Comment by Abhishek-569** [comment]
Hey @rberrelleza  I want to contribute to this project. Can you guide me to where the file related to the query is saved in the repo?

**Comment by jLopezbarb** [comment]
@rberrelleza I think this issue is already fixed by https://github.com/okteto/okteto/pull/3573. Could you confirm?

@Abhishek-569  Thanks for your interest, but since this issue is already done. Here are some issues suggested as `good for first issues`. If you want to work on any of these, just write and we will provide more context to help you troubleshoot, understand the code and fix the problem:
- https://github.com/okteto/okteto/issues/3596 
- https://github.com/okteto/okteto/issues/2057
- https://github.com/okteto/okteto/issues/3440
