### ISSUE TITLE
Duplicated line on selector

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3501]
**Describe the bug**
On the terminal if the information line is longer than the max width of the terminal in that moment. The information text is duplicated, which is annoying:
<img width="567" alt="Captura de Pantalla 2023-03-30 a las 11 55 17" src="https://user-images.githubusercontent.com/25170843/228799941-7083734d-4856-4dae-9c55-b564cfb2890d.png">

**To Reproduce**

1. Resize the terminal to not fit the information message
1. Run `okteto context`
1. Click on one of the arrow
1. See that the information line is duplicated

**Expected behavior**
The selector information should not be replicated

**Desktop (please complete the following information):**

- Terminal: warp
- Okteto version 2.14.0

**Comment by NitishKumar06** [comment]
HI, I'd like to work on this issue. Please assign this to me.

**Comment by jLopezbarb** [comment]
Hi @NitishKumar06 I've assigned the issue to you. Let us know if you have any problem trying to reproduce/understanding the issue and we will help you!!

**Comment by NitishKumar06** [comment]
I've reproduced this issue and went through this PR (https://github.com/okteto/okteto/pull/2461) to understand it. Could you provide some references that can help me in solving this issue?

**Comment by jLopezbarb** [comment]
Yep, that PR is the most similar one to fix this one and the one to look into for getting the most context for the bug. I guess the bug is produced either by [how we get the terminal width](https://github.com/okteto/okteto/blob/master/cmd/utils/selector.go#L417) or [how we calculate where the `\n` should be located.](https://github.com/okteto/okteto/blob/master/cmd/utils/selector.go#L425-L442)

We are using a `screenbuf` that doesn't detect when a new line should be added, and if the lenght is longer than the actual terminal width it duplicates the line. I think there might be a bug in that logic 

I'd start debugging the first section by printing `fmt.Println` the value of the terminal width. 
If the value is correct (probably whatever that is different to 0), I'd start debugging the algorithm to split the label in different lines and probably find a better way of implementing it

**Comment by NitishKumar06** [comment]
**Update (April 19, 2023):**

It's been two weeks since I'm working on solving this issue. Here's what I've understood up till now while understanding the code base. 

- The problem lies mainly in the  `func (s *OktetoSelector) renderLabel(sb *screenbuf.ScreenBuf)` function that is present in `cmd/utils/selectors.go` file at line 414. More precisely, either we're using the wrong way on how we get the _lines_. I'm not sure even what does _lines_ represent - Is it the number of lines added for a _labelLine_ whose length is greater than the terminal width? 
![image](https://user-images.githubusercontent.com/86051118/233166037-a202d53e-c5f6-489e-9a96-34f337bd2b40.png)
_If we observe carefully in the above picture, I have tried to print labelLine and lines on the terminal. For a labelLine "A context defines the..." the lines come out to be 1 whereas for a labelLine "Select the context..." that is consuming one extra line on the terminal to get fit, the lines come out to be 0._ This confuses me on what do we mean by lines here?  (comments are added by me just for an assumption --> assumption can be wrong too)

- If we look at the below code, the logic looks great. However, there can be an improvement in variable names to understand it better. For eg. _What is midLine representing? Is this representing the middle line of the labelLine whos length is larger than terminal width?_ Maybe Yes? Then why is it print statement giving output than it should be expected?

```
lastChar := 0 // represents the first character
for i := 0; i < lines+1; i++ {
    if lines == i {
        midLine := labelLine[lastChar:]
        labelLineBytes := render(s.OktetoTemplates.label, midLine)
	if _, err := sb.Write(labelLineBytes); err != nil {
		oktetoLog.Infof("error writing label: %s", err)
		}
	        break
	}
        midLine := labelLine[lastChar : lastChar+width]
        labelLineBytes := render(s.OktetoTemplates.label, midLine)
	if _, err := sb.Write(labelLineBytes); err != nil {
		oktetoLog.Infof("error writing label: %s", err)
	}
	lastChar += width			
 ```
 
![image](https://user-images.githubusercontent.com/86051118/233171213-0d069631-6494-4e65-a80e-41c1987decee.png)

Could anyone provide some references or their understanding looking at this code? My assumptions might be wrong but I'm looking forward to learning and solving this issue.

**Comment by jLopezbarb** [comment]
Hi @NitishKumar06, After reviewing that part of the code I think it's correct and the problem that is causing the bug is how we render the options. I have squared in red the part that is causing the bug. The lines where we render the text are https://github.com/okteto/okteto/blob/master/cmd/utils/selector.go#L225-L227. We will probably need to add something like what we do for the help text. 
![233171213-0d069631-6494-4e65-a80e-41c1987decee](https://user-images.githubusercontent.com/25170843/233304215-0a75d18a-ad3d-42b1-8f3a-a4bc016f8932.png)

**Comment by nitishfy** [comment]
Will be working on this as soon!

**Comment by jLopezbarb** [comment]
> Will continue working on this soon!

Let me know if you need anything else and I'll be glad to help you finding what's missing to complete the issue :)

**Comment by andreafalzetti** [comment]
Thanks for the update, @nitishfy 🙏
