### ISSUE TITLE
Wrong spinner on `okteto deploy --remote`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3572]
**Describe the bug**
Run `okteto deploy --remote` and the spinner says "Destroying your development environment..."

**Expected behavior**
- The spinner should say "Deploying your development environment..." if I run `okteto deploy --remote`.
- If I run `okteto destroy --remote`, the spinner should say "Destroying your development environment..."

**Comment by NitishKumar06** [comment]
This [PR](https://github.com/okteto/okteto/pull/3573) solves this issue.

**Comment by pchico83** [comment]
> This [PR](https://github.com/okteto/okteto/pull/3573) solves this issue.

Wow, that was fast @NitishKumar06 !

**Comment by NitishKumar06** [comment]
Thanks @pchico83! We are ready to close this issue now.

**Comment by AdrianPedriza** [comment]
Description updated. Now instead of display always `Deploying..` we are displaying `Destroying..`

**Comment by NitishKumar06** [comment]
I tried running this locally, and here's what I got:
![image](https://user-images.githubusercontent.com/86051118/234349480-b47de281-9dd0-469a-bfe6-6e1a221e9174.png)

**Comment by NitishKumar06** [comment]
I think the spinner is correct for `okteto deploy --remote`. I tried running the command `okteto destroy --remote` which showed spinner text as _Deploying your development environment_ instead of _Destroying your development environment_.

The spinner was way fast to analyse the output. Hence i screen recorded to see what text was showing up.

Hence, I think the issue description raised by @pchico83 was correct rather than the current one. 
![image](https://user-images.githubusercontent.com/86051118/234350710-bf1fbd23-499c-4831-91c9-ad9b83248234.png)

**Comment by jLopezbarb** [comment]
which Okteto CLI version are you using? It's only happening with the master build of the CLI. To reproduce it, run make build on the CLI project and then use that binary (probably ok alias if you have it pointing to the binary)

**Comment by AdrianPedriza** [comment]
Thinking about it we should have careful. This spinner I think is displayed when a remote executor (for destroy and deploy operation) is being built (logs from buildkit are not related to deploy/destroy command). We could confuse the user by displaying a message `Deploying/Destroying your dev env`  when, at the end, we are building the executor instead of deploying/destroying and env in that moment. I think the idea with this spinner was to communicate the user that we are preparing a remote executor but the env is not already deployed, I mean, we are displaying `Deploying your dev env`..  when the command (okteto deploy/destroy) has not yet been executed. I think a message saying `Building a remote executor..'  or something like that could fix this distinction between destroy/deploy. cc @pchico83

**Comment by pchico83** [comment]
> Thinking about it we should have careful. This spinner I think is displayed when a remote executor (for destroy and deploy operation) is being built (logs from buildkit are not related to deploy/destroy command). We could confuse the user by displaying a message `Deploying/Destroying your dev env` when, at the end, we are building the executor instead of deploying/destroying and env in that moment. I think the idea with this spinner was to communicate the user that we are preparing a remote executor but the env is not already deployed, I mean, we are displaying `Deploying your dev env`.. when the command (okteto deploy/destroy) has not yet been executed. I think a message saying `Building a remote executor..` or something like that could fix this distinction between destroy/deploy. cc @pchico83

@AdrianPedriza I think we show the spinner after each deploy command log output. There, it should be `Deploying/Destroying...`

**Comment by AdrianPedriza** [comment]
> > Thinking about it we should have careful. This spinner I think is displayed when a remote executor (for destroy and deploy operation) is being built (logs from buildkit are not related to deploy/destroy command). We could confuse the user by displaying a message `Deploying/Destroying your dev env` when, at the end, we are building the executor instead of deploying/destroying and env in that moment. I think the idea with this spinner was to communicate the user that we are preparing a remote executor but the env is not already deployed, I mean, we are displaying `Deploying your dev env`.. when the command (okteto deploy/destroy) has not yet been executed. I think a message saying `Building a remote executor..` or something like that could fix this distinction between destroy/deploy. cc @pchico83
> 
> @AdrianPedriza I think we show the spinner after each deploy command log output. There, it should be `Deploying/Destroying...`

oh yes, I got confused. Forget it then

**Comment by NitishKumar06** [comment]
Correct PR: https://github.com/okteto/okteto/pull/3585

**Comment by jLopezbarb** [comment]
Hi @NitishKumar06 Did we end up merging this PR? I see that there is one closed but I don't know if this is fixed

**Comment by NitishKumar06** [comment]
> Hi @NitishKumar06 Did we end up merging this PR? I see that there is one closed but I don't know if this is fixed

No, we're yet to fix this issue. The earlier merge was wrong and i'm working on it currently.

**Comment by pchico83** [comment]
@NitishKumar06 what's the current status? are we always showing "Destroying..."? if that's the case, it would be great if we can have the fix for the CLI 2.16.0 release

**Comment by NitishKumar06** [comment]
> @NitishKumar06 what's the current status? are we always showing "Destroying..."? if that's the case, it would be great if we can have the fix for the CLI 2.16.0 release

I've understood how to fix this though. Yes we're showing "Destroying..." but we can fix it. I've mentioned some query [here](https://github.com/okteto/okteto/pull/3584#discussion_r1195668394) and waiting for the reply. Meanwhile I'm trying to figure out way to implement the changes desired.

**Comment by NitishKumar06** [comment]
PR merged successfully. This issue is solved now. We can close this issue.

**Comment by jLopezbarb** [comment]
Closing it. Thanks again @NitishKumar06
