### ISSUE TITLE
`deploy` commands without output doesn't have an stage in the Okteto UI

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3596]
**Describe the bug**
If I have a deploy command that doesn't have output, the command doesn't show in the Okteto UI

**To Reproduce**

Deploy the following sample:
```
deploy:
  - echo foo
  - sleep 1
  - echo bar
```  

**Expected behavior**
- `sleep 1` appears in the Okteto UI

**Additional context**
The easiest solution is to always generate some artificial output, for example:
```
Executing command %s...
```
and `Command %s successfully executed` or `Command %s failed to execute`

**Comment by NitishKumar06** [comment]
Could you provide more context on this issue?
- What does it mean by _'deploy command that doesn't have output'_?
- _`sleep 1` appears in the Okteto UI_ - Are you mentioning about the Ui for Okteto CLI or Okteto Cloud?
- What behaviour do you expect in the below picture?

![image](https://github.com/okteto/okteto/assets/86051118/40bd2344-83b1-4942-b6b6-c18efa1790d0)

**Comment by jLopezbarb** [comment]
If you go to your cloud namespace (probably something like https://cloud.okteto.com/spaces/preview-nitishkumar06) You can check that the output shown there is something like: 
<img width="572" alt="Captura de Pantalla 2023-05-17 a las 13 04 59" src="https://github.com/okteto/okteto/assets/25170843/512ebe10-d95d-4b76-92c2-db8f23ba5a7c">

As you can see there is no stage for the sleep step. That's why we should add a message to the UI. 

Tip: If you don't want that the message is shown in the CLI you can use `oktetoLog.AddToBuffer` func

**Comment by NitishKumar06** [comment]
I'd like to take this up. Please assign this to me!

**Comment by NitishKumar06** [comment]
I'd like to test my changes at okteto cloud (UI), could you tell me how can I do that?
cc @jLopezbarb @pchico83

**Comment by pchico83** [comment]
@NitishKumar06 if you have access to Okteto Cloud, just deploy this manifest with `okteto deploy`:
```
deploy:
  - echo foo
  - sleep 1
  - echo bar
```
You should get you stages in the Okteto UI, instead of this two:
<img width="325" alt="Screenshot 2023-06-04 at 17 31 21" src="https://github.com/okteto/okteto/assets/7474696/fafc996a-1344-4393-b02e-b3f078584486">

**Comment by NitishKumar06** [comment]
**Update:** I'm working on this. 
- Do we plan to display the stage like _Run  "sleep i"_?
- @pchico83 mentioned that _The easiest solution is to create an artificial output._. I want to confirm whether we are planning to put the text on CLI, yes?

**Comment by pchico83** [comment]
@NitishKumar06 yes to both. the "artificial" output would show on the command out put and the Okteto UI

**Comment by nitishfy** [comment]
I've got a little bit of understanding of the logic and believe that the change needs to be made [here](https://github.com/okteto/okteto/blob/master/cmd/deploy/local.go#L226), right? 

1. How do we check whether a command is a correct command or not? I'm assuming [this](https://github.com/okteto/okteto/blob/master/cmd/deploy/local.go#L205) line maybe does that. Can someone confirm it?

2. I've tried removing `oktetoLog.SetStage("")` and found the results as in this picture:
![image](https://github.com/okteto/okteto/assets/86051118/4ee67008-acec-4acd-addc-6dbb33dba63a)

I'm figuring out why the logs are displayed like in this order? (maybe because of loop [here](https://github.com/okteto/okteto/blob/master/cmd/deploy/local.go#L201), but how?) 
Would someone be willing to provide some context over it?

**Comment by pchico83** [comment]
@nitishfy after [setting the stage](https://github.com/okteto/okteto/blob/master/cmd/deploy/local.go#L205) you can add a line to `oktetoLog.AddToBuffer` a message like `Executing command %s..., command.name`. Then, [here](https://github.com/okteto/okteto/blob/master/cmd/deploy/local.go#L209) means the command has been successfully executed, you can `oktetoLog.AddToBuffer` a message like `Command %s successfully executed, command.name`

**Comment by nitishfy** [comment]
**Update:** [PR](https://github.com/okteto/okteto/pull/3701) raised!
