### ISSUE TITLE
okteto CLI doesn't recognize a cluster with okteto installed if you pick one of the clusters added via kubeconfig

### ISSUE THREAD

**Issue by RinkiyaKeDad** [okteto/okteto#3792]
**Describe the bug**
I have a GKE cluster where I installed Okteto. Since the cluster is present in my `kubeconfig` it starts showing in the list when I do `okteto ctx use`. But when I select it and try to deploy a repository, it says:

```
 x  'build.api-dev.image' is required if your cluster doesn't have Okteto installed
```
Which isn't correct. It works when I add the context by specifying the Okteto URL.

** Steps to replicate**
- Create a cluster and add it to your kubeconfig
- Install Okteto in it
- Choose the cluster from `okteto ctx use` 
- Run `okteto deploy` or `okteto up` from the movies app
It will fail with the message that the cluster doesn't have Okteto installed.
- Add the cluster via the URL for the Okteto installation (for example: `https://demo.okteto.com`)
- Run `okteto deploy` or `okteto up` from the movies app.

It will now work even though the cluster you have chosen is technically the same one. 

**Expected behavior**
Ideally, it should work when I choose the cluster from the `okteto ctx use` list without even adding via the URL. But if that's not possible maybe we can update the error message to say to add the cluster to the context via the URL instead of saying that the cluster doesn't have Okteto installed, which can be confusing.

**Comment by ifbyol** [comment]
This is the expected behavior. One thing is the Kubernetes context as a vanilla cluster and other thing is the Okteto context.

Choosing a Kubernetes context from the list, it will use the context as a vanilla cluster (I might want to do an `okteto up` in a service not managed by Okteto as my Kubernetes cluster might have more things apart from Okteto). To connect to the Okteto context, you would need to use the Okteto url as you just did.

Agree with the message. It might be confusing. We might update the message to something like `'build.api-dev.image' is required if your context is not an Okteto one` or similar. My point is to focus on the "context" used not in the "cluster"

**Comment by RinkiyaKeDad** [comment]
Seems like an easy fix. Let's add the `good-first-issue` label to this to see if any new contributors want to pick this up :)

**Comment by RinkiyaKeDad** [comment]
Commenting to remove the `stale` label
