### ISSUE TITLE
Remove deprecated dev metadata fields

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3795]
## Parent epic/feature

* Feature: [Okteto CLI 3.0](https://www.notion.so/okteto/Okteto-CLI-3-0-Epic-2-Default-to-remote-and-remove-deprecated-features-64f818252e6944d88186f7572e4e1294?pvs=4)

## Description

Remove the fields `dev.annotations` and `dev.labels` 
These commands have been replaced `dev.metadata.labels`, `dev.metadata.annotations` and `dev.selector` to achieve the previous behaviour

## Acceptance Criteria

- [ ] An error is produced when using `dev.annotations` or `dev.labels` 
- [ ] Test that  `dev.metadata.labels`,`dev.metadata.annotations` and `dev.selector` works in the exact same way as it is now

**Comment by rishitashaw** [comment]
Hi team,

I'm writing to contribute a change to the translateDeprecatedMetadataFields() function in `pkg/model/dev.go`.

The current function prints a warning if the labels or annotations fields are used in a Dev manifest. I propose to modify the function to throw an error instead of a warning. This would make it clear to users that the deprecated fields should not be used.


Here is the proposed change:

```shell
func (dev *Dev) translateDeprecatedMetadataFields() {
  if len(dev.Labels) > 0 {
    panic("The field `labels` is deprecated and should not be used. Use the field `selector` instead.")
  }

  if len(dev.Annotations) > 0 {
    panic("The field `annotations` is deprecated and should not be used. Use the field `metadata.annotations` instead.")
  }

  for indx, s := range dev.Services {
    if len(s.Labels) > 0 {
      panic(
        "The field `%s.labels` is deprecated and should not be used. Use the field `selector` instead.",
        s.Name,
      )
    }

    if len(s.Annotations) > 0 {
      panic(
        "The field `annotations` is deprecated and should not be used. Use the field `%s.metadata.annotations` instead.",
        s.Name,
      )
    }
  }
}

```

I think this change is important because it will help to ensure that users are aware of the deprecated fields and that they are not used in new manifests.

I would be happy to implement this change and submit a PR. Please let me know if you have any questions.

Thanks,
Rishita Shaw

**Comment by andreafalzetti** [comment]
Thanks for contributing with your ideas, @rishitashaw!

In Go, it's preferred to return errors instead of throwing expections, like panicking. Also, deprecation is a great way to let the users know something is about to change, giving them time to migrate, if you throw an expections, it's blocking them from using the product.

**Comment by rishitashaw** [comment]
I made the requested changes to handle deprecated fields in the Okteto CLI. Instead of warnings, the updated code returns errors for each deprecated field. This ensures clarity while allowing users to continue using the product.

Could you quickly review the modified code and let me know if it aligns with your expectations?
```shell
func (dev *Dev) translateDeprecatedMetadataFields() error {
	if len(dev.Labels) > 0 {
		message := "The field 'labels' is deprecated and will be removed in a future version. Use the field 'selector' instead (https://okteto.com/docs/reference/manifest/#selector)"
		for k, v := range dev.Labels {
			dev.Selector[k] = v
		}
		return errors.New(message)
	}

	if len(dev.Annotations) > 0 {
		message := "The field 'annotations' is deprecated and will be removed in a future version. Use the field 'metadata.annotations' instead (https://okteto.com/docs/reference/manifest/#metadata)"
		for k, v := range dev.Annotations {
			dev.Metadata.Annotations[k] = v
		}
		return errors.New(message)
	}

	for indx, s := range dev.Services {
		if len(s.Labels) > 0 {
			message := fmt.Sprintf("The field '%s.labels' is deprecated and will be removed in a future version. Use the field 'selector' instead (https://okteto.com/docs/reference/manifest/#selector)", s.Name)
			for k, v := range s.Labels {
				dev.Services[indx].Selector[k] = v
			}
			return errors.New(message)
		}

		if len(s.Annotations) > 0 {
			message := fmt.Sprintf("The field 'annotations' is deprecated and will be removed in a future version. Use the field '%s.metadata.annotations' instead (https://okteto.com/docs/reference/manifest/#metadata)", s.Name)
			for k, v := range s.Annotations {
				dev.Services[indx].Metadata.Annotations[k] = v
			}
			return errors.New(message)
		}
	}

	return nil
}

```

**Comment by rishitashaw** [comment]
Hi @andreafalzetti,

I'm writing to follow up on my previous message about the change to the translateDeprecatedMetadataFields() function in pkg/model/dev.go.

In addition, I'll modify the error messages in the following format to maintain idomaticity in the code: `return fmt.Errorf(errorMessage)`

I'd like to ask if you'd be willing to assign this change to me so that I can start working on it. I'm happy to answer any questions you have.

Thanks,
Rishita

**Comment by andreafalzetti** [comment]
Hi @rishitashaw, apologies for the delay in getting back to you. Any code change must be submitted via a PR, it's hard to review from comments in issues as there is no diff and I don't know what you're modifying. 

I'll assign this issue to you, feel free to submit a PR if you like!

**Comment by andreafalzetti** [comment]
Thanks for your interest in contributing to the Okteto CLI, @khareyash05.

I am afraid that at the moment we are not onboarding new contributors to the project. We are focusing on development and we don't have bandwith for tasks that are not in our upcoming set of priorities.

Thanks again :)
