### ISSUE TITLE
[CLI Quality][CI] Improve the `release` workflows

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#3830]
As part of the CLI Quality initiative, some pains where identified regarding the workflows that currently exist when performing a release of the okteto project.

## Acceptance criteria

- [ ] Review `release`, `release-dev`, `release-branch` workflows
- [ ] Release workflows should be "retriggeable"
- [ ] Unit-test should only be run once

Any other improvement should be proposed and implemented and reviewed at this PRs

**Comment by nitishfy** [comment]
Hi, Can I take this up?

**Comment by AdrianPedriza** [comment]
Hi @nitishfy ! unfortunately, this task is intended for a team member as it has to do with our CLI quality initiative as well as working with our current chosen CI/CD tool (CircleCI) with which you need permissions only given to the team.  Thanks for your initiative anyway, it is appreciated!

**Comment by AdrianPedriza** [comment]
## Proposed improvements

### workflows

- `release`:
    - I propose to remove any test jobs on the workflow. Seems they are never used. That jobs ignore all branches and all release tags. https://github.com/okteto/okteto/blob/master/.circleci/config.yml#L456-L467
    - it is not necessary to wait for the `build-binaries` job to complete.  This is already done by waiting for the `push-image-tag` job (it waits for `build-binaries`) https://github.com/okteto/okteto/blob/master/.circleci/config.yml#L480
- `release-dev`:
    -  run the e2e since it is a nightly workflow (it does not matter a priori that it takes longer to complete the workflow). It will be in the dev channel so having e2e test coverage on it may add value to that release in terms of confidence. If we decide to parallelize, I propose to not parallelize this workflow since nightly speed is not a priority in my opinion.
    - I propose not to upload the image to the registry if the tests do not pass. We do not want a failed binary in the dev channel.
    - it is not necessary to wait for the `build-binaries` job. By waiting for the `push-iamge-tag` job, we are indirectly already waiting for `build-binaries`.
- `release-branch`:
    - the unix e2e tests run but not the windows ones. I propose that the windows e2e tests should also be added.
    - it is not necessary to wait for the `build-binaries` job. By waiting for the `test-integration` job, we are indirectly already waiting for `build-binaries`.

### retrigger the release workflow

sometimes, when retrieving from the release workflow, the `release-external` job fails because there is no change to the repo https://github.com/okteto/homebrew-cli.git. I propose that the script must take this case into account, avoiding returning an exit 1 returned by [the command of the script](https://github.com/okteto/okteto/blob/master/scripts/update_homebrew_formula.sh#L71) when trying to git commit without any change.

### unit and e2e tests

- when the user runs the tests explicitly (currently using the `_e2e`/`_win` branch suffix) in my opinion it is not expected to run the unit tests as well. I propose to eliminate the unit test job in this case.
- parallelize jobs running e2e test. I would only parallelize the `deploy` and `up` tests, which are the ones that take significantly longer. Parallelizing more tests makes me doubt the value it adds vs the expense in terms of infra.

**Comment by teresaromero** [comment]
looks good, have you taken a look into the circleci testing command? this will allow us to retrigger only test included at a workflow and not repeat it https://circleci.com/docs/test-splitting-tutorial/ 

What could be the best approach to test circleci jobs? https://circleci.com/blog/local-pipeline-development/ this looks helpful 🤔

**Comment by jLopezbarb** [comment]
I'll comment the points I don't agree 100% with them:


### Release dev

Right now we don't track these ci anywhere. Should we track them?

> run the e2e since it is a nightly workflow (it does not matter a priori that it takes longer to complete the workflow). It will be in the dev channel so having e2e test coverage on it may add value to that release in terms of confidence. If we decide to parallelize, I propose to not parallelize this workflow since nightly speed is not a priority in my opinion.

I agree but if you can, do it with circleci tests so we can rerun those who failed because of flakiness

> `I propose not to upload the image to the registry if the tests do not pass. We do not want a failed binary in the dev channel.` 

If the build fails we don't upload a failed binary so we are getting the previous one

### retrigger the release workflow
 
 I'd separate every push to a different job: push to brew/push GHactions/push to docker. Making idempotent the script is a must but I'd add them in different jobs so if one fails we don't block the others

### unit and e2e test

>  when the user runs the e2e tests explicitly (currently using the _e2e/_win branch suffix) in my opinion it is not expected to run the unit tests as well. I propose to eliminate the unit test job in this case.

I wouldn't eliminate them since it's the only way for the contributors to run them without our manual intervention. If we agree on just using the manual intervention is ok for me but I'd discuss it before doing it
