### ISSUE TITLE
Preserve original command in dev container

### ISSUE THREAD

**Issue by phoenix-bjoern** [okteto/okteto#3835]
We are using supervisord to start several services like nginx, php-fpm, postfix, crontab etc. This services are required to handle http traffic etc. So when the dev container replaces the original container command, the container does not work correctly.

To restore the original command we trick the dev container command in the manifest:

```
dev:
  mycontainer:
    command: "bash -c 'nohup /run.sh &'; bash"
```

This is pretty odd.

Wouldn't it be a better option if okteto would deploy as a sidecar? If okteto would duplicate the original container of the deployment/statefulset, including env vars, volume mounts etc., it could change the command without changing the actual functionality of the original container. Since RWO volumes can be shared between sidecars the synchronized files are still identical in  the two containers.
When sharing the same process namespace (https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/) you could even start and stop process.

This alternative deployment option however might not be desirable for all users.

I see two possible changes in the configuration to deploy the dev container as a sidecar:

1. Introduce a new "dev.mycontainer.sidecar: true" bool variable.
2. Abuse of "dev.mycontainer.container" and set it to a non-existing container name (which currently results in an error, see #3834).

Looking forward to discuss this proposal.

**Comment by phoenix-bjoern** [comment]
The approach described maybe offers and alternative to #351.

**Comment by phoenix-bjoern** [comment]
Any idea how to solve this issue?

**Comment by jLopezbarb** [comment]
Hi @phoenix-bjoern, It's something that we have been discussing around but it's something that is not in our roadmap yet. The problem with a side container is that it could cause some race conditions because  okteto starts several services like syncthing and an SSH server in order to work.

I don't know if it's an option but you can specify your [own init container in your dev manifest](https://www.okteto.com/docs/reference/manifest/#initcontainer-object-optional). Our [init image](https://github.com/okteto/bin-image) is public and you can add the initialisation of your services after it. Let me know if that works, if not we will look into another solution but it's something that we want to tackle during the following weeks
