### ISSUE TITLE
If my Okteto manifest is specifying some `resources.limits` but not `resources.requests` we are setting the limits as requests

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#3838]
**Describe the bug**

When my Okteto manifest specifies some limits in the resources, but not requests, we are setting the limits also as requests. That generates issues in some scenarios as the limits are usually greater numbers but requests should be smaller ones, so there might be scheduling issues if the numbers are high

**To Reproduce**

1. Deploy a dev environment
2. Generate an Okteto manifest to connect to one of its services. In the dev section within that service, add `resources.limits.cpu` and `resources.limits.memory`
3. Execute `okteto up` in that service
4. If you check the pod spec, you will see that `requests` are `limits` are the same.

**Expected behavior**

If I don't specify any request, we shouldn't use the limit, we should leave it empty and let the cluster set the requests automatically

**Desktop (please complete the following information):**

- Version: tested with `2.18` but this behavior is probably old

**Additional context**
Here is the documentation on how to set resources in the dev container: https://www.okteto.com/docs/reference/manifest/#resources-object-optional

**Comment by teresaromero** [comment]
I've been able to reproduce this behaviour. Unfortunately, there is no code reference where we force this condition when limit is specified but not requests.

This is happening because kubernetes force this condition when creating the pod when only limit is specified
https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#if-you-specify-a-cpu-limit-but-do-not-specify-a-cpu-request
