### ISSUE TITLE
Exclude one or more applications in a namespace from sleeping

### ISSUE THREAD

**Issue by proof-nicholas** [okteto/okteto#3858]
**Is your feature request related to a problem? Please describe.**
We use AWS localstack free version which provisions all resources in memory.  When Okteto sleeps our namespace, it results in the state of the localstack application being lost which causes issues with Terraform managing the resources.  We would love a feature that allows us to exclude one or more applications from being put to sleep.  

**Describe the solution you'd like**
Allow adding a label or annotation to a deployment that would exclude it from being put to sleep while all other resources in the namespace are put to sleep.

**Comment by jLopezbarb** [comment]
Hi @proof-nicholas, 
You can add `dev.okteto.com/persistent` in an specific deployment or statefulset. You can check our [documentation page](https://www.okteto.com/docs/administration/cleanup/#persistent-resources--) about that in order to get more insight

I'll close the issue for now. Please feel free to reopen the issue and let us know if the problem persists after using the given annotation

**Comment by proof-nicholas** [comment]
Excellent, just what I was looking for, thanks!
