### ISSUE TITLE
`okteto destroy` on remote display confusing logs

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/okteto#3862]
**Describe the bug**
when I run `okteto destroy` using remote feature, the output shows and stage `Running stage 'Destroying configmap'` but, as a user, I've no intention to deploy/destroy any configmap

**To Reproduce**

1. Clone okteto/movies
1. In folder repo, exec `okteto destroy --remote`
2. Check command output
<img width="524" alt="Captura de Pantalla 2023-08-01 a las 8 19 04" src="https://github.com/okteto/okteto/assets/22500940/00d96def-be77-4cbf-8d86-8b9aabf820d0">

**Expected behavior**
Dev environment should be removed but, as a user, I don't expect any log related to a resource that I've never deployed. Configmap deletion should be a debug log.

**Comment by nitishfy** [comment]
Hi, I'd like to take this up. Please assign this to me!

**Comment by andreafalzetti** [comment]
Hey @nitishfy, welcome back 👋  As you may have seen in other issues, we are not onboarding new contributors because we're trying to stay focus on priorities and don't have bandwith to help new contributors. If you feel you have enough context to work on this, given all your previous contributions, I don't see why not.

So you know, we are aiming to increase code-coverage of the project, so all PRs must meet high standards of testing and at least 75% of coverage. That includes if we modify existing files which are not covered by tests.

happy coding! :)

**Comment by nitishfy** [comment]
No worries Andrea! Having previously worked on such issues before, I think I'll be able to come up with a solution to this soon. FYI, the mentorship period just got over and I'm currently dealing with exams. I'll start working on this issue once I have a good bandwidth. Mentioning about code-coverage, I'll make sure that a good amount of testing is done before I raise the final PR.
