### ISSUE TITLE
When I execute `okteto ctx` command with --insecure-skip-tls-verify flag, the `Insecure mode enabled` message is displayed twice

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#3885]
**Describe the bug**

When I execute `okteto ctx` with `--insecure-skip-tls-verify` flag, a warning message `! Insecure mode enabled` is displayed twice

<img width="959" alt="Captura de pantalla 2023-08-04 a las 18 45 10" src="https://github.com/okteto/okteto/assets/3510171/e847ca0b-b423-44f4-aa61-7b7182c63340">

**To Reproduce**

1. Execute `okteto ctx use https://cloud.okteto.com --insecure-skip-tls-verify`

**Expected behavior**

The warning message is displayed only once

**Desktop (please complete the following information):**

Checking with different versions it seems that started to happen in `2.17.x` version

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by nitishfy** [comment]
I'll solve this issue. Please assign this to me!

**Comment by jLopezbarb** [comment]
Assigned!! I don't know how trivial this one is, but let us know if you face any problem and we'll try to give you some tips

**Comment by nitishfy** [comment]
> Assigned!! I don't know how trivial this one is, but let us know if you face any problem and we'll try to give you some tips

I'm late for this but I've done my research. Here's what I have found after debugging:

The function `PersistentPreRun` is being called twice, first for the `cmd` and then for the `context` command. Everytime it is called, it is always going to be executing the `okteto.SetInsecureSkipTLSVerifyPolicy(ctxOptions.InsecureSkipTlsVerify)` function.

```
if parent := cmd.Parent(); parent != nil {
	if parent.PersistentPreRun != nil {
	   parent.PersistentPreRun(parent, args)
	}
}
```

When the `parent.PersistentPreRun()` function is called recursively for the first time, it changes it's value to `main.main()` due to which we are facing the above issue. For every recursive call, the function `okteto.SetInsecureSkipTLSVerifyPolicy(ctxOptions.InsecureSkipTlsVerify)` is called.

I think one way we can solve this is by either calling the function before the _If_ statement OR setting up a boolean flag/count pointer.

cc: @jLopezbarb

**Comment by andreafalzetti** [comment]
The change seems requiring some refactoring in order to make the change testable and avoid any workaround. I am removing the `good first issue` label because such change should be done and owned by the CLI team. Apologies agian @nitishfy and thanks for all your contributions 🙇
