### ISSUE TITLE
Dev sessions get disconnected with "The server has asked for the client to provide credentials (get deployments.apps)`

### ISSUE THREAD

**Issue by cowgod** [okteto/okteto#4013]
Historically, my dev sessions (`okteto up`) were always very stable, staying up through my entire working day, and even automatically reconnecting when opening up my laptop. Since upgrading to Okteto CLI 2.20, my sessions go down after a few minutes, giving the message:

```
 x  The server has asked for the client to provide credentials (get deployments.apps)
    Find additional logs at: /Users/<username>/.okteto/<namespace>/www-php/okteto.log
```

**To Reproduce**

1. Run `okteto up` in a project directory
1. Wait 15-60 minutes
1. See that connection has been disconnected

**Expected behavior**
Connection to dev container remains online and stable until `okteto down` command is issued.

**Desktop (please complete the following information):**

- OS: macOS
- Version: Ventura 13.5.2 (22G91)

**Additional context**
My Okteto is a self-hosted instance running in AWS EKS.

- Okteto chart version: 1.12.0
- Okteto app version: 6013b7d7
- Kubernetes version: 1.26.0
- The Admin page in the Okteto web interface reports a CLI version of 2.19.2
- Currently installed Okteto CLI version on local machine is 2.20.0

**Comment by jLopezbarb** [comment]
Hi @cowgod,

We released [Okteto CLI 2.21.0](https://github.com/okteto/okteto/releases/tag/2.21.0) that refreshes your token so you don't need to run okteto up again in order to refresh your token.

If you need to stick with the current CLI version you can always use `OKTETO_USE_STATIC_KUBETOKEN` environment variable in order to use the previous static token method although we discourage using it because the new token is safer. You can find more information about it [here](https://www.okteto.com/docs/cloud/credentials/#using-your-kubernetes-credentials).

Hope this information is useful and if you still face any problem with either of the solutions don't hesitate to reopen the issue again.

Happy coding!!
