### ISSUE TITLE
running "okteto context delete" on a kubernetes context doesn't delete the context, nor the command fails

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#4130]
**Describe the bug**
running "okteto context delete" on a kubernetes context doesn't delete the context, nor the command fails. 

**To Reproduce**

1. Run "okteto context list" (if you don't have a kubernetes context, add one)
1. Run "okteto context delete <kubernetes-context-name>"
1. Run "okteto context list"
1. context still shows

**Expected behavior**
Id expect the context to be deleted. If we don't want to support this, the I'd expect the command to fail with an error or an informational message about it. 

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.23.2

**Comment by andreafalzetti** [comment]
I can reproduce this behavior and I want to add extra info to explain what's happening.

Regardless if the user adds the vanilla k8s context to the okteto config (via `okteto ctx use <context>`), the CLI detects k8s clusters by parsing the user `.kube/config`. This means, that I have potentially N contexts that I don't have in my `~/.okteto/context/config.json`, so when I delete them, I don't really delete them because they were automatically discovered and added to the `okteto ctx list` output.

You could add one explicitly by running `okteto ctx use <context>`, which would add it to the Okteto config, however from a user's perspective, it's the same, because removing it would effectively remove it from our config, but it would be discovered automatically again when listing contexts.

The options that I see here are:

1. Returning an error when attempting to delete a context that does not belong to the Okteto config (ie. `This context cannot be deleted because it was automatically discovered from yoru ~/.kube/config.`) Possibly inviting the user to update their kube config, if needed. Or potentially ask for confirmation, and update the kube config from the CLI.
2. Create a property in our config with the list of "deleted" vanilla clusters, so that we don't display them automatically. If the user adds the context again, we could remove it from this list, so it would appear agin.

**Comment by ifbyol** [comment]
@pchico83 @codyjlandstrom @rlamana I think we need to think about this from a product perspective. I agree the experience is odd for the customer as they might think that the command didn't work.

I think modifying the command help to highlight the fact that kubernetes contexts cannot be deleted and raising an error with a descriptive message when that scenarios happens would be the best option. I don't think we should write in the kubeconfig
