### ISSUE TITLE
envFrom secrets are not available in hybrid mode

### ISSUE THREAD

**Issue by roderik** [okteto/okteto#4193]
**Describe the bug**

I've been trying out hybrid mode on a local cluster with just the cli. And according to the docs, my locally running service should get the environment values of the pod in the cluster. That works for env vars defined on the deployment directly, but not from     envFrom secrets.

```
    envFrom:
    - secretRef:
        name: api
```

The secrets in there are not in process.env.

In the busy box image they are there when i run printenv

**Desktop (please complete the following information):**

- OS: macOS, Orbstack cluster
- Version: 2.25.2

**Comment by jLopezbarb** [comment]
Hi @roderik, We have an open [PR](https://github.com/okteto/okteto/pull/4194) fixing the bug you described that should be included in the next CLI release. For now, if you want to get the secret in your container, you can use the [valueFrom](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-a-container-environment-variable-with-data-from-a-single-secret) field from the k8s manifest instead of using `envFrom`.
