### ISSUE TITLE
Feature Request: okteto config view

### ISSUE THREAD

**Issue by danielhelfand** [okteto/okteto#551]
**Describe the solution you'd like**

I would like the ability to see what is in my local configuration (`okteto.yml`) in a user friendly manner via the okteto CLI. While there is limited information available now via the file, my assumption is that it will eventually hold more information that could be useful for a user to view before running `okteto up`. 

In general, I think it would be nice to have more information than what is available in `okteto.yml` as well as part of a command like this. Something that captures a complete picture of the development environment a user is working with so he or she can make  informed decisions about if everything looks correct. 

**Describe alternatives you've considered**

All the information described above can be found via various sources and tools besides okteto, but it would be nice to aggregate that information together with an okteto command. 

**Additional context**

I think it would be helpful to discuss relevant data that should be captured as part of this in this issue before proceeding, but I think basic information like the programming language to be used, the container image to be used, and what namespace is being worked in are easy points to start with.

**Comment by pchico83** [comment]
Hi @danielhelfand 
I am so happy to see this issue opened because we are right in the process of defining a more self-contained okteto manifest, and your input is much appreciated.
We are considering to specify which k8s resources must be created as part of your dev environment (k8s deployments, k8s services...) or even having our own manifest for deployments to make it simpler for developers to deploy/upgrade microservices as part of their dev environments.
It would be something similar to docker-compose and it would understand our okteto persistent volumes to support remote volume mounts.
What do you think about this?

**Comment by danielhelfand** [comment]
@pchico83 I like the sound of this a lot! I'm glad to hear it's on the roadmap.

I like the idea of some type of guided process for setting up an environment, opinionated defaults from `okteto init`, and certainly also love the idea of custom manifests. Think all of these options will support a lot of levels of knowledge for using okteto.

I think this would certainly help bring together a lot of the information I would be looking for with this feature.
