### ISSUE TITLE
Add labels and annotations to the service and deployment created by okteto

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#933]
**Is your feature request related to a problem? Please describe.**
I have a running application. Instead of "swapping" a deployment, I want to be able to spin up a "dev" copy of a deployment and have isitio redirect traffic. "okteto up" already creates the svc and deployment for me, but istio requires specific labels to be applied.

**Describe the solution you'd like**
I'd like to be able to tell to okteto to add certain labels/annotations to the service and deployments it creates, so it can integrate with other tools.

**Describe alternatives you've considered**
I can run a script post okteto up, but it adds more complexity when compared to just okteto up.

**Comment by rberrelleza** [comment]
We could extend the `annotations` feature we have now to also include labels and to apply them to the service we created.

Another option is to have a more formal "template" version or something to allow people to fully customize the resources we create.

**Comment by rberrelleza** [comment]
https://kubernetes.slack.com/archives/CM1QMQGS0/p1592409922473100 -> the original conversation

**Comment by stevejr** [comment]
As an update I managed to get this working without any changes to Okteto. The missing labels on the new kubernetes service that Okteto creates was not the issue as Istio Destination Rules is actually looking at the labels in pod resources. This means I can do the following:

-  create a new deployment of my microservice by setting the `name` field in my okteto.yaml to a different value that the currently deployed microservice. This causes okteto to create a new kubernetes deployment/service
- create an Istio Destination Rule and Virtual Service resource for my new okteto deployment using the `app` label that okteto sets in the deployment and is based on the `name` field from the okteto.yaml
- update my existing Virtual Service object with the desired traffic management rules so that I route to my newly deployed kubernetes service

Now, what would be a great feature enhancement to Okteto would be to create the Istio resources and also update the existing ones in the cluster.

**Comment by pchico83** [comment]
@stevejr do you have available the manifests that you apply before/after `okteto up` to configure istio?
I already have a cluster with istio running :-)

**Comment by stevejr** [comment]
@pchico83 - Please see attached files. The Pre-Okteto file is to setup Istio for all services and the Post-Okteto file is just for the Catalogue service (This is all for the Instana Robot Shop app - http://github.com/instana/robot-shop).

Note that in the Post-Okteto Virtual Service for Catalogue I am using a different hostname for the Okteto version of my service.

[Pre-Okteto-Istio.zip](https://github.com/okteto/okteto/files/4820453/Pre-Okteto-Istio.zip)

[Catalogue-Post-Okteto-Istio.zip](https://github.com/okteto/okteto/files/4820474/Catalogue-Post-Okteto-Istio.zip)

**Comment by pchico83** [comment]
@stevejr thanks! I will give an update probably the next week, this one is already packed :-(

**Comment by pchico83** [comment]
@stevejr sorry, we have been very busy these months :-(
I have added this issue to the September plan.

**Comment by pchico83** [comment]
@stevejr could you send me an email to pablo@okteto.com?

We have a prototype for integrating `okteto up` with service meshes, I would like to share it with you
